services:
  temporal-extraction-machamp:
    build:
      context: ./machamp
    ports:
      - 5300:5000
    restart: unless-stopped
    networks:
      - temporal_extraction_network
    container_name: temporal_extraction_machamp_container
    image: temporal_extraction_machamp_image

networks:
  temporal_extraction_network:
