services:
  temporal-extraction:
    build:
      context: ./build
    ports:
      - 5300:5000
    restart: unless-stopped
    networks:
      - temporal_extraction_network
    container_name: temporal_extraction_container
    image: temporal_extraction_image

networks:
  temporal_extraction_network:
